name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i
      - name: Install dependencies for Ts
        run: npm install --save-dev @types/bcryptjs@^2.4.6 @types/chai@^5.0.1 @types/chai-http@^3.0.5 @types/express@^4.17.21 @types/express-serve-static-core@^5.0.1 @types/jsonwebtoken@^9.0.7 @types/mocha@^10.0.9 @types/node@^22.9.0 @types/supertest@^6.0.2 chai@^5.1.2 cross-env@^7.0.3 mocha@^10.8.2 supertest@^7.0.0 ts-node@^10.9.2 ts-node-dev@^2.0.0 typescript@^5.6.3
        
      - name: Run TypeScript compiler
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run security tests
        run: npm audit
